version: '3.8'

services:
  # Our Node.js server
  server:
    # Build the Docker image from the current directory
    build: .
    
    # Map port 5000 from the container to port 5000 on your machine
    ports:
      - "5000:5000"
    
    # Set environment variables
    environment:
      - NODE_ENV=production
      - PORT=5000
    
    # Restart policy - automatically restart if the container crashes
    restart: unless-stopped
    
    # Give the container a friendly name
    container_name: cv-builder-server
    
    # Optional: Add Redis if your app needs it
    # Uncomment the lines below if you want to include Redis
    # depends_on:
    #   - redis
    # environment:
    #   - REDIS_URL=redis://redis:6379

  # Optional: Redis service (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   container_name: cv-builder-redis 